markdown: GFM
title: Vivek Joshi
description: "Hi I'm Vivek, and I'm an ex-hotelier based in Delhi, India upskilled in data analytics. My portfolio includes projects around data analysis and data visualization."
